### ISSUE TITLE
ctrl2cap

### ISSUE THREAD

**Issue by aagarwal584** [baohaojun/system-config#10]
Hi Baohaojun,
Please see a question regarding the sysinternal tools.  Specifically, concerned tool is ctrl2cap.  Is there a way to modify tool to convert "~" character to another character?  Default behavior is to convert "CAPS LOCK" to "Left CONTROL".
Thanks.
Regards,
aagarwal584

**Comment by baohaojun** [comment]
I have not used Windows system in years, so can't help you, sorry.
