### ISSUE TITLE
env文件打开乱码，文件是dos格式的，linux下安装有问题，需要一个个改回来

### ISSUE THREAD

**Issue by xushaobo** [baohaojun/system-config#12]
下面这样的错误应该也是格式问题引起的
/usr/bin/env: 'perl\r': No such file or directory

**Comment by baohaojun** [comment]
能不能告诉我一下是哪个文件？我找了一圈都没有找到。

**Comment by xushaobo** [comment]
ish@debian:~$ ~/system-config/bin/Linux/after-check-out.sh 
bash: /home/manbofish/system-config/bin/Linux/after-check-out.sh: /bin/bash^M: bad interpreter: No such file or directory

**Comment by baohaojun** [comment]
可能你的环境有问题，从github上下载的源码吗？下载下来到你的机器上怎么就变成dos格式了呢？我自己看到的都是Unix的换行符。
