### ISSUE TITLE
Error in Shares.cs

### ISSUE THREAD

**Issue by ststeiger** [baohaojun/system-config#4]
There's an error in 
https://github.com/baohaojun/system-config/blob/master/gcode/enum-share/shares/Shares.cs

it only works on x86, not on x64. 

Instead of 
for (int i = 0, lpItem = pBuffer.ToInt32(); i < entriesRead; i++, lpItem += offset)
use this
for (long i = 0, lpItem = pBuffer.ToInt64(); i < entriesRead; i++, lpItem += offset)

then it works on both x86 & x64 (AnyCPU)

**Comment by baohaojun** [comment]
I don't know why I have that code, now I'm deleting it, since it's not used by me at all.

Thanks for pointing it out:D
