### ISSUE TITLE
sawfish配置文件没有生效，删除也一样

### ISSUE THREAD

**Issue by xushaobo** [baohaojun/system-config#8]

**Comment by xushaobo** [comment]
Error goes:
Waiting for the previous manager to go away.
Sawfish error:
File error: No such file or directory, gnome
Sawfish error:
File error: No such file or directory, bhj-run-application

**Comment by baohaojun** [comment]
You can try to Start it from desktop Manager such as gnome desktop manager. For the second line,  it is actually normal. I see this line too.

For the last line, you need to find where this file is in my system config, and why sawfish cannot find this file. In my setup script I made a symlink of this file into your home directory's .sawfish/lisp/.
