### ISSUE TITLE
包老师，请教您一个问题

### ISSUE THREAD

**Issue by PowerfulSpider** [baohaojun/system-config#9]
包老师，开这个issue，主要是我有一个问题想请教您。

我是东南大学的一名本科生，之前在学习emacs的时候偶然间在bilibili上看到了您的视频，看完视频之后我对system-config产生了很大的兴趣。所以我就装了一下您的system-config，由于缺乏说明文档，system-config里面很多的功能我并不知道如何使用，并且安装完之后报的一些错我也不知道如何解决（且报错的这些功能我暂时可能也用不到）。与其查看源码，我想不如参考您的system-config自己也写一个system-config，根据自己的需求要什么功能添加什么功能。（本人的system config地址是：https://github.com/PowerfulSpider/system_config）

由于我非常喜欢 "做选择题“，所以我自己写的re命令也是列举历史让用户选择，具体如下：
user@user-OptiPlex-3046:~/system_config
$ re git clone
0) git clone git@192.168.3.15:data-integration/com.kgtdata.qa.joyoung.git
1) git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
2) git clone https://github.com/pein0119/emacs.d.git
3) git clone git@github.com:PowerfulSpider/system_config.git
=> emacs
0) git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
1) git clone https://github.com/pein0119/emacs.d.git
=> 1

目前，我的做法是选中了一个命令之后，将该命令放到系统剪贴板里面，之后就可以直接粘贴出来
但是其实我想做成的效果是将选中的命令直接上屏，所以我想请教您如何将选中的命令直接上屏？

我已经尝试了我能想到的方法：在终端中模拟用户输入（没找到有用资料）；修改PS1（这个最傻：））；调用alt + p 输入字符查找与字符相接近的历史命令（没弄清楚alt + p调用了什么函数，因此也就不知道在脚本中怎么调用）

谢谢！

**Comment by baohaojun** [comment]
你好，我是用bash的自动补齐机制实现的上屏。没错，bash的补齐机制可以自己编程扩展，请参考 .bash_completion.d/re。

re的人机界面确实非常不友好😅。你想在我的环境下试一下re的话，先运行一下hir，然后再输入re并且不要回车，而是按tab键。想补齐git clone的话，输入 re git clone，然后按tab键。

**Comment by PowerfulSpider** [comment]
看来要研究一下bash completion了，谢谢包老师的解惑：）
